version: '3'
services:
  psql:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/treegram
    ports:
      - "3000:3000"
    depends_on:
      - psql
  sh:
    build: .
    command: bash
    volumes:
      - .:/treegram
    depends_on:
      - psql
  dump:
    image: mdillon/postgis
    volumes:
      - ./tmp/dumps:/dumps
    depends_on:
      - psql
    command: bash # "pg_dump -Fc -f /dumps/$(date +%s).pgdump -U postgres -h psql treegram_development"
